module: JellyfinAPI
generate:
- entities
- paths
- enums
fileHeaderComment: |
  //
  // jellyfin-sdk-swift is subject to the terms of the Mozilla Public
  // License, v2.0. If a copy of the MPL was not distributed with this
  // file, you can obtain one at https://mozilla.org/MPL/2.0/.
  //
  // Copyright (c) 2022 Jellyfin & Jellyfin Contributors
  //
entities:
  includeIdentifiableConformance: true
  sortPropertiesAlphabetically: true
  exclude:
  - BaseItemDto.CurrentProgram
  alwaysIncludeDecodableImplementation: false
  alwaysIncludeEncodableImplementation: false
paths:
  style: operations
  filenameTemplate: "%0API.swift"
