name: Generate stable API

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        ref: 'main'

    - name: Clone SwagGen
      run: "git clone https://github.com/yonaskolb/SwagGen.git"
      
    - name: Run SwagGen
      run: "cd SwagGen && swift run swaggen generate https://api.jellyfin.org/openapi/jellyfin-openapi-stable.json --option name:SwiftFinAPI"
      
    - name: Commit new changes to the repo
      run: |
        git config user.name jellyfin-bot
        git config user.email team@jellyfin.org
        git pull
        git add .
        git commit -m "Update stable OpenAPI client" || echo
        git push
