name: Generate stable API

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        ref: 'main'

    - name: Download bow-openapi
      run: |
        curl -s https://api.github.com/repos/bow-swift/bow-openapi/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")' | xargs -I {} wget -O - https://github.com/bow-swift/bow-openapi/archive/{}.tar.gz | tar xz
    
    - name: Install bow-openapi
      run: |
        sudo make linux -C bow-openapi-*
      
    - name: Generate
      uses: workflow/nix-shell-action@v1
      with:
        interpreter: bash
        packages: bash
        script: bow-openapi --name JellyfinOpenAPI --schema https://api.jellyfin.org/openapi/jellyfin-openapi-stable.json --output /github/workspace/

    # "echo" in commit returns true so the build succeeds, even if no changed files
    - name: Commit new changes to the repo
      if: ${{ steps.diff.outputs.count }} > 0
      run: |
        git config user.name jellyfin-bot
        git config user.email team@jellyfin.org
        git pull
        git add .
        git commit -m "Update stable OpenAPI client" || echo
        git push
